[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x', 'postgresql']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm run build:client',
  'npm run build:server',
  'npx prisma generate',
  'npx prisma migrate deploy',
  'npx tsx prisma/seed.ts'
]

[start]
cmd = 'node server/dist/server/index.js'
