[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x', 'postgresql']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm run build:client',
  'npm run build:server',
  'npx prisma generate'
]

[start]
cmd = 'npx prisma migrate deploy && npx tsx prisma/seed.ts && node server/dist/server/index.js'
