[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/dist/server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[databases.postgresql]
version = "14"
